export const GET_BUSINESS_REWARDS_REQUEST ='GET_BUSINESS_REWARDS_REQUEST';
export const GET_BUSINESS_REWARDS_STARTED ='GET_BUSINESS_REWARDS_STARTED';
export const GET_BUSINESS_REWARDS_SUCCESS ='GET_BUSINESS_REWARDS_SUCCESS';
export const GET_BUSINESS_REWARDS_FAILURE ='GET_BUSINESS_REWARDS_FAILURE';

export const GET_PREGNANCY_LIST_REQUEST ='GET_PREGNANCY_LIST_REQUEST';
export const GET_PREGNANCY_LIST_STARTED ='GET_PREGNANCY_LIST_STARTED';
export const GET_PREGNANCY_LIST_SUCCESS ='GET_PREGNANCY_LIST_SUCCESS';
export const GET_PREGNANCY_LIST_FAILURE ='GET_PREGNANCY_LIST_FAILURE';

export const GET_DASHBOARD_LIST_REQUEST ='GET_DASHBOARD_LIST_REQUEST';
export const GET_DASHBOARD_LIST_STARTED ='GET_DASHBOARD_LIST_STARTED';
export const GET_DASHBOARD_LIST_SUCCESS ='GET_DASHBOARD_LIST_SUCCESS';
export const GET_DASHBOARD_LIST_FAILURE ='GET_DASHBOARD_LIST_FAILURE';

export const GET_FORMFREPORT_LIST_REQUEST ='GET_FORMFREPORT_LIST_REQUEST';
export const GET_FORMFREPORT_LIST_STARTED ='GET_FORMFREPORT_LIST_STARTED';
export const GET_FORMFREPORT_LIST_SUCCESS ='GET_FORMFREPORT_LIST_SUCCESS';
export const GET_FORMFREPORT_LIST_FAILURE ='GET_FORMFREPORT_LIST_FAILURE';

